### PR TITLE
fix: remove ReDoS regexp

### LINKED ISSUE #501: Vulnerable Regular Expression
The following regular expression used in the "o" formatter is vulnerable to ReDoS:
```js
/\s*\n\s*/
```
The slowdown is moderately low: for 50.000 characters around 2 seconds matching time. However, I would still suggest one of the following: 
- remove the regex,
- anchor the regex,
- limit the number of characters that can be matched by the repetition,
- limit the input size.

If needed, I can provide an actual example showing the slowdown.

### PR DESCRIPTION
**Pull request by zhuangya**
- split the line by '\n',
- and trim each line(do we really need to trim each line?).
- then join each line by ' '

i think this is the same as the original RegExp, correct me if wrong.

fix #501

### CODE REVIEW

**Comment by TooTallNate** [comment]
Thank you!

**Comment by dougwilson** [comment]
Can this be backported to the 2.x series?

**Comment by TooTallNate** [comment]
@dougwilson Sure thing: https://github.com/visionmedia/debug/releases/tag/2.6.9

Curious what's holding you back from upgrading though 😅

**Comment by worakanya1985** [comment]
redos

**Comment by jcmarcfloress** [comment]
Thank  you

**Pull request merged**
