### PR TITLE
node: allow msDiff disable

### PR DESCRIPTION
**Pull request by dotmilk**
#187

### CODE REVIEW

**Comment by iamsebastian** [comment]
If looks fine, would anybody be able to merge this? @TooTallNate maybe?

**Comment by dkebler** [comment]
Indeed, if this branch is ok to merge please do so and release.  Thx.

**Comment by world** [comment]
This feature is dope. I have forked from tooDeadNate and pulled this gem into my repo. I mean WTF would the default be to measure ms with every single debug invocation with no ability to turn it off. Default noise is noise. Thank you @cheshirecatalyst!

**Comment by cheshirecatalyst** [comment]
@TooTallNate Any thoughts on this?

**Comment by monolithed** [comment]
It's really painful
img-2016-09-12-19-46-39

I like the idea to turn off time logging, but I suggest using something like `DEBUG=-time`

**Comment by thebigredgeek** [comment]
@TooTallNate thoughts here?

**Comment by thebigredgeek** [comment]
@dotmilk can you update code so that we can consider a merge?

**Comment by dotmilk** [comment]
@thebigredgeek I don't even have this repo laying around anymore.

**Comment by thebigredgeek** [comment]
Thanks for letting us know :)

**Pull request closed without merging**
