### PR TITLE
Using custom logger loaded in domain.

### PR DESCRIPTION
**Pull request by FernandoMorais**
Adding domain capability to able folks to use custom logger (winston) loaded in a domain context.

### CODE REVIEW

**Comment by DevSide** [comment]
I'm pretty sure debug doesn't want to work with a CQRS solution and an other loging library.

**Comment by TooTallNate** [comment]
Why not just override the `debug.log` property? (see the [Readme](https://github.com/visionmedia/debug#stderr-vs-stdout) for an example)

**Comment by thebigredgeek** [comment]
The VS file should probably also disappear

**Comment by thebigredgeek** [comment]
I'm closing this for now.  Feel free to re-open if you feel that overriding `debug.log` prop (see readme) isn't a decent solution

**Pull request closed without merging**
