### PR TITLE
Added yarn integration to Makefile

### PR DESCRIPTION
**Pull request by thebigredgeek**

### CODE REVIEW

**Comment by thebigredgeek** [comment]
@TooTallNate

**Comment by TooTallNate** [comment]
This essentially only affects development, though I'm not sure if we should be committing/publishing the yarn.lock file

**Comment by paulirish** [comment]
I asked the yarn team about this and they recommend keeping the lockfile in git.

https://yarnpkg.com/en/docs/version-control#toc-required-files sez "The following files must be checked into source control for anyone to be able "

**Comment by thebigredgeek** [comment]
Yeah I also heard that we should check in the lockfile @TooTallNate @paulirish

**Comment by thebigredgeek** [comment]
BTW, sorry about the branch directly in the repo.  Old habits (from work) die hard haha

**Comment by TooTallNate** [comment]
I guess it doesn't hurt. Feels kind of dirty committing a "generated" file like that. Same as `npm-shrinkwrap.json` in the end I suppose.

**Comment by TooTallNate** [comment]
> BTW, sorry about the branch directly in the repo.

I don't particularly mind. That's what git is for 😸

**Pull request merged**
