### PR TITLE
Use WorkerLocation to detect web worker

### PR DESCRIPTION
**Pull request by jetzhliu**
Almost all browsers support web worker also support color logger.
Also fix some environment similar to web but not support document variable(like react-native).

### CODE REVIEW

**Comment by botverse** [comment]
Unfortunately this won't fix other similar cases as per #240

**Comment by DevSide** [comment]
This PR is a first step.

@botverse, why would you consider a web worker as a specific case/environment like Electron or React Native ?

**Comment by botverse** [comment]
They are examples of the same case, neither windows or document are available.

**Comment by DevSide** [comment]
Web workers are in the browser scope. Two lines of code to make debug compatible them until a better solution show up looks good enough, don't you think ?

**Comment by thebigredgeek** [comment]
There are conflicts, unfortunately.  Can you please update?

**Comment by thebigredgeek** [comment]
@DevSide can you explain how this would work?  `window.document` doesn't exist in a web worker.  Closing this for now until we can find a more robust fix

**Comment by jetzhliu** [comment]
@thebigredgeek 
This PR only make `debug` knowing that it can support color logging in a web worker environment.
It may not useful for other environment to detect whether it support color logging, but I has used this PR to work with `react-native` chrome debugging for almost half a year.

**Comment by thebigredgeek** [comment]
Fixed @ https://github.com/visionmedia/debug/pull/298

**Pull request closed without merging**
