### PR TITLE
chore: add Node.js 10, remove Node.js 4

### PR DESCRIPTION
**Pull request by DanielRuf**

### CODE REVIEW

**Comment by Qix-** [comment]
Thanks!

**Comment by jtyjty99999** [comment]
br??

**Comment by popomore** [comment]
It should be a breaking change, why it is published as semver minor.

**Comment by Qix-** [comment]
@popomore how is this a breaking change?

**Comment by jtyjty99999** [comment]
br？？

**Comment by popomore** [comment]
@qix the package or application use debug on Node 4 is broken after this version published.

**Pull request merged**
