### PR TITLE
cleanup browser tests and fix null reference check on window.documentElement.style.WebkitAppearance

### PR DESCRIPTION
**Pull request by thebigredgeek**

### CODE REVIEW

**Comment by thebigredgeek** [comment]
@TooTallNate can you do a sanity check on this for me?

**Comment by thebigredgeek** [comment]
also fixes https://github.com/visionmedia/debug/issues/436

**Comment by darrachequesne** [comment]
@thebigredgeek I think this has broken webworker compatibility (introduced by https://github.com/visionmedia/debug/issues/382)

**Comment by thebigredgeek** [comment]
@darrachequesne whoops!  That was sloppy of me!  I knew I should have waited for the sanity check from @TooTallNate haha.  I just deprecated 2.6.5 and released 2.6.6 with a fix.  You should be able to unpin

**Comment by darrachequesne** [comment]
@thebigredgeek great, thanks!

**Comment by TooTallNate** [comment]
Damnit, this GitHub Reviews feature tripped me up. First time using it. I had these comments written out 2 days ago and I thought they were visible. Turns out I had to hit the "Submit Review" button first. My bad.

**Pull request merged**
