### PR TITLE
fix #467

### LINKED ISSUE #467: webpack.DefinePlugin and process.env.DEBUG
My webpack config:
```
...
plugins: [
  new webpack.DefinePlugin({
    'process.env': {
      NODE_ENV: JSON.stringify('production'),
      DEBUG: true
    }
  })
],

target: 'electron-main',
...
```

So webpack changes
`process.env.DEBUG = namespaces;`
to
`true = namespaces;`
which leading to error
`ReferenceError: Invalid left-hand side in assignment`

### PR DESCRIPTION
**Pull request by errorx666**

### CODE REVIEW

**Comment by errorx666** [comment]
As stated in #467, if using webpack's `DefinePlugin` will rewrite `process.env.DEBUG` to a literal `true` or `false`.

The function becomes:
```js
function save(namespaces) {
  if (null == namespaces) {
    // If you set a process.env field to null or undefined, it gets cast to the
    // string 'null' or 'undefined'. Just delete instead.
    delete true; // syntax error
  } else {
    true = namespaces; // syntax error
  }
}
```

With this patch, we avoid assigning to an r-value.

This is currently blocking me from using the bcrypt library.

**Comment by Qix-** [comment]
Please put all of that into a comment, and don't alias as it's confusing (I thought the aliasing fixed something bizarre, hence my previous comment).

**Comment by errorx666** [comment]
I added the comment.

**Comment by Qix-** [comment]
Sorry it took me so long to get to this. Any chance you could rebase off master?

**Comment by Qix-** [comment]
Actually, I've changed my mind on this - please see https://github.com/visionmedia/debug/issues/467#issuecomment-448419976.

**Pull request closed without merging**
