### PR TITLE
#719 - Support decoration with process information

### PR DESCRIPTION
**Pull request by dbo**
Implements #719 

Feedback welcome.

### CODE REVIEW

**Comment by Qix-** [comment]
Really not a fan of adding more environment variables - this is what #556 is aimed to solve. Otherwise, every logging combination under the sun would scope-creep this package into oblivion.

**Comment by dbo** [comment]
@Qix- Apparently it's not really about my own logs only (which I could customize with what is aimed in #556), but about 3rd party NPMs that I use in my process. Moreover, environment variables don't require to execute any custom code which is sometimes not possible when plugging into frameworks that use their own startup scripts. Since all debug env variables are scoped to `DEBUG_` I don't see any collision.

**Comment by Qix-** [comment]
It's not about collision, it's about API cleanliness. The idea behind #556 is that it'd be globally enforced and entirely backwards compatible. You wouldn't have to modify code, but instead use `-r` to inject a non-default reporter.

In the case of PID's, #582 could be used here as well.

**Comment by dbo** [comment]
@Qix- I agree, reading on #582 I think it's what I look for, since I could streamline all logs to carry the PID (needs some `%P` or whatever extension though) or define a readable process title.

**Pull request closed without merging**
