### PR TITLE
Library should not contains lockfile

### PR DESCRIPTION
**Pull request by fengmk2**
see https://medium.com/@boennemann/avoid-yarn-for-packages-and-fully-enjoy-its-benefits-for-application-development-8bdd4deb33cf

### CODE REVIEW

**Comment by TooTallNate** [comment]
This makes sense to me 👍

**Comment by thebigredgeek** [comment]
Hmm.  Yeah good points all around.  Can you add to .gitignore and .npmignore please @fengmk2 ?

**Comment by fengmk2** [comment]
@thebigredgeek Added!

**Comment by thebigredgeek** [comment]
@fengmk2 thanks merging.  As a note, if you are using Yarn, use pure mode to avoid caching in lockfiles

**Comment by fengmk2** [comment]
@thebigredgeek yep, I know how yarn work.

**Comment by thebigredgeek** [comment]
Kk.  Just trying to be helpful :D.  I didn't know about that option until I read up more on it.  Been busy with work.  Started using Yarn to simply save time during build debugging haha

**Comment by fengmk2** [comment]
Yep, yarn install is very fast after lockfile created.
We're using [npminstall](https://github.com/cnpm/npminstall) to doing the same job, and it don't need lockfile but install still very fast!

**Pull request merged**
