### PR TITLE
Add option to hide namespace in logs

### PR DESCRIPTION
**Pull request by donatas**
Our log collector expects the output to be of some format (across systems, that write logs) and now the only thing I can't control is the namespace, prepended to each line. 

It's enabled by default, passing environment variable allows hiding it.

PR contains tests that cover default behavior (namespace + log) and the new feature.

### CODE REVIEW

**Comment by donatas** [comment]
@TooTallNate please review

**Comment by donatas** [comment]
@thebigredgeek @nkolban

**Comment by Qix-** [comment]
Hi there - I'm :-1: personally with adding yet another env var. Could you weigh in on #582?

**Comment by Qix-** [comment]
Closing in favor of #582.

**Pull request closed without merging**
