### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by frank-dspeed**
Made Clear what a namespace is in the projet Terminology as many people like me would think that the prefix is the namespace

```js
const myDebuger = require('debug')('namespace')
```

### CODE REVIEW

**Comment by Qix-** [comment]
This is entirely incorrect. I'm not surr what's confusing you but the namespace is what you pass to Debug initially. The example is very clear.

Also, please don't use "u" as a replacement for "you" in technical literature. Ever.

**Comment by frank-dspeed** [comment]
@Qix- your confusing me as i told you https://github.com/visionmedia/debug/issues/665 in this issue that it did Not Change the output color based on what i supplyed inital to it

**Comment by Qix-** [comment]
Please re-read what I wrote in that comment. I was very clear.

**Comment by frank-dspeed** [comment]
@Qix- ok i should stop to inform you about stuff i understand but i was also very clear your simply wrong as my terminal supports more colors then red and the problem is Not a coincidence.
but anyway i like this lib its ok for me i can use it without colors i only wanted to report that 

i hope that now made sense for you

**Comment by Qix-** [comment]
@frank-dspeed Please **re-read** what I wrote. It is a coincidence that both of those namespaces are red. Try other namespaces or install `supports-color` to support more colors. I don't know how to spell it out any other way.

**Pull request closed without merging**
