### PR TITLE
added parameter to useColors to allow setting an override

### LINKED ISSUE #246: useColors should take an override parameter and save it
I'm using debug in a Qt-WebKit application and debug falsely thinks it can handle color.

It would be nice if users could call useColors with a parameter to set an override.

### PR DESCRIPTION
**Pull request by jandrieu**
Resolves #246

### CODE REVIEW

**Comment by jandrieu** [comment]
Hmmm... after I made that change, I saw the TODO to add a 'localStorage' variable.  Maybe that's a better option...  This fix works for my use case, however. Maybe you'll like it.

**Comment by poshaughnessy** [comment]
We're trying to use debug in a Cordova application, using a Cordova plugin to output console.logs as native logs. It would be good to force-disable the colours, since our native app logs come out looking like "%c this %c".

I would vote for making it a simple parameter rather than having to store a value in localStorage!

**Comment by thebigredgeek** [comment]
@jandrieu I think this would possibly work better as an environment variable on the server.  On the client, we probably also want to respect `process.env` namespace (as is frequently done with webpack)

**Comment by thebigredgeek** [comment]
@TooTallNate thoughts?  Using an environment variable like `DEBUG_COLORS=false` might be a good solution here.  Also solves https://github.com/visionmedia/debug/pull/211

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/issues/314

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/issues/309

**Comment by thebigredgeek** [comment]
Need to update code @jandrieu

**Comment by jandrieu** [comment]
I don't think the environment variable solves my use case.  I use debug in a custom browser, with my code bundled with browserified. The browser can't handle the colors and I don't believe browserify has a way to pass environment variables to debug.

This patch allows the javascript within the page to turn colors on/off programmatically. My custom browser provides enough information that the script can detect that it is running in a normal browser or my custom browser, then the script calls use colors to set true/false.

**Comment by thebigredgeek** [comment]
@jandrieu check out middleware proposal here.  would love your input so that v3 supports your needs with this.

https://github.com/visionmedia/debug/pull/247

**Comment by thebigredgeek** [comment]
closing for now

**Comment by thebigredgeek** [comment]
https://github.com/visionmedia/debug/issues/370 Middleware should allow for this

**Comment by gpbl** [comment]
@thebigredgeek how does it work? I can’t see any docs about middlewares :(

**Pull request closed without merging**
