### PR TITLE
181 stderr vs stdout

### PR DESCRIPTION
**Pull request by dmarcelino**
Updated stderr vs stdout based on #181

### CODE REVIEW

**Comment by TooTallNate** [comment]
Thanks!

**Comment by dmarcelino** [comment]
No problem

**Comment by VipSaran** [comment]
The current stdout.js example:
```
var debug = require('../');
var log = debug('app:log');

// by default console.log is used
log('goes to stdout!');

var error = debug('app:error');
// set this namespace to log via console.error
error.log = console.error.bind(console); // don't forget to bind to console!
error('goes to stderr');
log('still goes to stdout!');

// set all output to go via console.warn
// overrides all per-namespace log settings
debug.log = console.warn.bind(console);
log('now goes to stderr via console.warn');
error('still goes to stderr, but via console.warn now');
```
has wrong output!
When looking only at the stdout-console, it produces:
```
$ DEBUG=* node stdout.js 1> /dev/stdout 2> /dev/null
$ 
```
(so nothing), but this was expected:
```
$ DEBUG=* node stdout.js 1> /dev/stdout 2> /dev/null
  app:log goes to stdout! +0ms
  app:log still goes to stdout! +46ms
```

and when inspecting the error-console output, it produces:
```
$ DEBUG=* node stdout.js 2> /dev/stdout 1> /dev/null
  app:log goes to stdout! +0ms
  app:error goes to stderr +104ms
  app:log still goes to stdout! +46ms
```
bu this is expected:
```
$ DEBUG=* node stdout.js 2> /dev/stdout 1> /dev/null
  app:error goes to stderr +104ms
```

**Comment by dmarcelino** [comment]
@VipSaran... the example you posted is not the most up to date, check [here](https://github.com/visionmedia/debug/blob/master/example/stdout.js)

My outputs from latest master:

``` sh
DEBUG=* node example/stdout.js 1>/dev/stdout 2>/dev/null 
Fri, 13 Mar 2015 19:58:33 GMT app:log goes to stdout
Fri, 13 Mar 2015 19:58:33 GMT app:error now goes to stdout via console.info
Fri, 13 Mar 2015 19:58:33 GMT app:log still goes to stdout, but via console.info now
```

```sh
DEBUG=* node example/stdout.js 1>/dev/null 2>/dev/stderr 
  app:error goes to stderr! +0ms
  app:error still goes to stderr! +0ms
```

Which is what's expected.

**Comment by VipSaran** [comment]
Yea. Thats the correct/expected output. I must have been looking at the wrong commit.

**Pull request merged**
