### PR TITLE
Adds package lock file.

### PR DESCRIPTION
**Pull request by HarrySarson**
npm advises that `package-lock.json` be checked into version control.

See https://docs.npmjs.com/files/package-locks#using-locked-packages.

### CODE REVIEW

**Comment by TooTallNate** [comment]
Thanks for the PR! 💜

Frankly I don't agree that `package-lock.json` should be committed to version control in the context of modules. For end-applications it makes sense but not for modules, where it just gets ignored upon `npm install` anyways.

**Comment by HarrySarson** [comment]
Fair. :)

**Comment by HarrySarson** [comment]
In that case should package-lock.json be added to gitignore? Otherwise it hangs around as an versioned file.

**Comment by TooTallNate** [comment]
Ya good call e7e568a24736486721882282eb21beb31c741647

**Pull request closed without merging**
