### PR TITLE
update "debug" to v1.0.0

### PR DESCRIPTION
**Pull request by dougwilson**
This updates the dependency. AFAIK there are no code changes; just a promotion to 1.0.0

### CODE REVIEW

**Comment by TooTallNate** [comment]
Commit message is confusing. `s/debug/ms/` 😉

**Comment by dougwilson** [comment]
lol, oops! That was a weird mistake to make there :embarrassing:

**Comment by thebigredgeek** [comment]
@TooTallNate we can just reword it before we update changelog.  That's what I was planning to do anyway :)

**Comment by popomore** [comment]
ms has released 2.0.0 for security issue https://github.com/zeit/ms/pull/89

**Pull request merged**
