### PR TITLE
- use simple for loop instead of forEach

### PR DESCRIPTION
**Pull request by knalbandianbrightgrove**
Babel is not transforming on runtime such things like forEach which is critical when a product going to be used as SaaS solution.
I have everything to transpile ES6 code, but some specific methods make me sad.
I would appreciate if you approve this small change

Thank you in advance!

### CODE REVIEW

**Comment by Qix-** [comment]
`.forEach` has been around since ES5. Your loop is also incredibly inefficient, pulling `Object.keys()` each iteration.

There is no reason why this should be merged, nor should the existing code be causing you problems. If Babel is transpiling this incorrectly, please open an issue with them.

**Comment by knalbandianbrightgrove** [comment]
@Qix- 
Thank you for the quick response.

I made a type when talk about ES6, originally I mean ES5.

Babel is not transpiling .forEach, it should be polyfilled. So in order to prevent extra polyfilled 

One more argument is that in this file you already using the same idea, please take a look
https://github.com/knalbandianbrightgrove/debug/blob/88584c3ecbcee0447e4ff37018085106ec34ef2b/src/common.js#L184

**Comment by Qix-** [comment]
It's not transpiling down to es3? What ancient browser are you targeting?

**Comment by knalbandianbrightgrove** [comment]
@Qix- it does transpiling everything but not methods, in order to work with such things like Array.prorotype.forEach you should use babel-polyfill. I need to support IE8+.
I do not see any performance downgrade in switching to for loop if you care about performance

**Comment by knalbandianbrightgrove** [comment]
@Qix- sorry for disturbing you.

Any logic reason to not approve this PR?

**Comment by Qix-** [comment]
Babel 7 includes support for this, your PR is for compatibility reasons that are caused by user error. It doesn't make any improvement to me. Please open an issue with Babel if polyfilling isn't working as expected.

**Comment by knalbandianbrightgrove** [comment]
@Qix- Please refer to this line https://github.com/knalbandianbrightgrove/debug/blob/88584c3ecbcee0447e4ff37018085106ec34ef2b/src/common.js#L184

And change it to forEach

**Pull request closed without merging**
