### PR TITLE
Deprecate DEBUG_FD

### PR DESCRIPTION
**Pull request by TooTallNate**
First step of #386.

### CODE REVIEW

**Comment by Shiroh1ge** [comment]
An error concerning this debug_fd got me here: DeprecationWarning: `DEBUG_FD` is deprecated. Can anyone  explain what it is and how to get rid of it? Is it safe?

**Comment by thebigredgeek** [comment]
It's safe

**Comment by thebigredgeek** [comment]
Just make sure to stop using DEBUG_FD becore 3.0

**Comment by Shiroh1ge** [comment]
Thanks!!

**Pull request merged**
