### PR TITLE
supportsColor.level => supportsColor.stdout.level

### PR DESCRIPTION
**Pull request by cw881014**
you wrote wrong

```
console.log(supportsColor.level)
undefined

console.log(supportsColor.stdout.level >= 2)
true
```

### CODE REVIEW

**Comment by TooTallNate** [comment]
This is because of `supports-color@5` [breaking API change](https://github.com/chalk/supports-color/pull/64) (/cc @Qix-).

It's probably easy enough to check both APIs for now in `debug`?

**Comment by Qix-** [comment]
Yeah so use `(supportsColor.stdout || supportsColor).level` and then probably use stderr because I believe we use it instead of stdout (can you confirm @TooTallNate?)

**Comment by TooTallNate** [comment]
Yes, `supportsColor.stderr` please.

**Comment by realityking** [comment]
This can be closed, it was fixed with 285dfe10a5c06d4a86176b54bef2d7591eedaf40

**Pull request closed without merging**
